//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Application.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string AddressNotValid {
            get {
                return ResourceManager.GetString("AddressNotValid", resourceCulture);
            }
        }
        
        public static string PhoneNumberNotValid {
            get {
                return ResourceManager.GetString("PhoneNumberNotValid", resourceCulture);
            }
        }
        
        public static string AddressCannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("AddressCannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        public static string PhoneCannotBeNullOfEmpty {
            get {
                return ResourceManager.GetString("PhoneCannotBeNullOfEmpty", resourceCulture);
            }
        }
        
        public static string OfficeNotFound {
            get {
                return ResourceManager.GetString("OfficeNotFound", resourceCulture);
            }
        }
        
        public static string PhotoNotFound {
            get {
                return ResourceManager.GetString("PhotoNotFound", resourceCulture);
            }
        }
        
        public static string NothingChanged {
            get {
                return ResourceManager.GetString("NothingChanged", resourceCulture);
            }
        }
        
        public static string PageSettingCannotBeNull {
            get {
                return ResourceManager.GetString("PageSettingCannotBeNull", resourceCulture);
            }
        }
        
        public static string PageMustBeGrateWhenZero {
            get {
                return ResourceManager.GetString("PageMustBeGrateWhenZero", resourceCulture);
            }
        }
        
        public static string PageSizeMustBeGraterThenZero {
            get {
                return ResourceManager.GetString("PageSizeMustBeGraterThenZero", resourceCulture);
            }
        }
        
        public static string CountryCanNotBeEmpty {
            get {
                return ResourceManager.GetString("CountryCanNotBeEmpty", resourceCulture);
            }
        }
    }
}
