services:
  mongo:
    container_name: mongo
    image: mongo:latest
    networks:
      - offices-network
    ports:
      - "27017:27017"
      - "28017:28017"
networks:
  offices-network:
    driver: bridge

  
  