#
services:
#  # general services
#  elastic:
#    extends: 
#      file: docker-compose.general.yaml
#      service: elastic
#  kibana:
#    extends: 
#      file: docker-compose.general.yaml
#      service: kibana
#
#  # auth service
#  db-auth:
#    extends:
#      file: docker-compose.auth.yaml
#      service: db-ms
#    depends_on:
#      - elastic
#  redis:
#    extends:
#      file: docker-compose.auth.yaml
#      service: redis
#  auth:
#    extends:
#      file: docker-compose.auth.yaml
#      service: auth
#    deploy:
#      mode: replicated
#      replicas: 1
#      placement:
#        constraints:
#          - node.labels.type == auth
#      restart_policy:
#        condition: on-failure
#    ports:
#      - "4000:4000"
#      - "4001:4001"
#    depends_on:
#      - db-auth
#  # offices service
  db-postgres:
    extends:
      file: docker-compose.general.yaml
      service: db-postgres
#    depends_on:
#      - elastic
    ports:
      - "5432:5432"
  mongo:
    extends:
      file: docker-compose.general.yaml
      service: mongo
#  offices:
#    extends:
#      file: docker-compose.offices.yaml
#      service: office
#    deploy:
#      mode: replicated
#      replicas: 1
#      placement:
#        constraints:
#          - node.labels.type == offices
#      restart_policy:
#        condition: on-failure



networks:
  elastic:
    driver: bridge
  identity:
    driver: bridge
    
volumes:
  database-data: