global using FluentAssertions;
global using Moq;
global using Xunit;
global using Application.Services.Auth;
global using AuthTests.Fixtures;
global using Domain.Models;
global using Bogus;
global using Application.OperationResult.Errors;
global using Application.OperationResult.Results;