//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presentation.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Presentation.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        internal static string GoToRegister {
            get {
                return ResourceManager.GetString("GoToRegister", resourceCulture);
            }
        }
        
        internal static string GoToLogin {
            get {
                return ResourceManager.GetString("GoToLogin", resourceCulture);
            }
        }
        
        internal static string IncorrectCredentials {
            get {
                return ResourceManager.GetString("IncorrectCredentials", resourceCulture);
            }
        }
        
        internal static string EmalNotValid {
            get {
                return ResourceManager.GetString("EmalNotValid", resourceCulture);
            }
        }
        
        internal static string PasswordMinLenght {
            get {
                return ResourceManager.GetString("PasswordMinLenght", resourceCulture);
            }
        }
        
        internal static string PasswordMaxLenght {
            get {
                return ResourceManager.GetString("PasswordMaxLenght", resourceCulture);
            }
        }
        
        internal static string PassordSymbols {
            get {
                return ResourceManager.GetString("PassordSymbols", resourceCulture);
            }
        }
        
        internal static string InputEmail {
            get {
                return ResourceManager.GetString("InputEmail", resourceCulture);
            }
        }
        
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        internal static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        internal static string InputPassword {
            get {
                return ResourceManager.GetString("InputPassword", resourceCulture);
            }
        }
        
        internal static string InputConfirmPassword {
            get {
                return ResourceManager.GetString("InputConfirmPassword", resourceCulture);
            }
        }
        
        internal static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        internal static string LoginSuccessed {
            get {
                return ResourceManager.GetString("LoginSuccessed", resourceCulture);
            }
        }
    }
}
