//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presentation.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NavigationResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NavigationResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Presentation.Resources.NavigationResources", typeof(NavigationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        internal static string Email_ {
            get {
                return ResourceManager.GetString("Email:", resourceCulture);
            }
        }
        
        internal static string Password_ {
            get {
                return ResourceManager.GetString("Password:", resourceCulture);
            }
        }
        
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        internal static string Patients {
            get {
                return ResourceManager.GetString("Patients", resourceCulture);
            }
        }
        
        internal static string Doctors {
            get {
                return ResourceManager.GetString("Doctors", resourceCulture);
            }
        }
        
        internal static string Receptionists {
            get {
                return ResourceManager.GetString("Receptionists", resourceCulture);
            }
        }
        
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        internal static string ShowProfile {
            get {
                return ResourceManager.GetString("ShowProfile", resourceCulture);
            }
        }
        
        internal static string InputPassword {
            get {
                return ResourceManager.GetString("InputPassword", resourceCulture);
            }
        }
        
        internal static string InputEmail {
            get {
                return ResourceManager.GetString("InputEmail", resourceCulture);
            }
        }
        
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        internal static string Doctor {
            get {
                return ResourceManager.GetString("Doctor", resourceCulture);
            }
        }
        
        internal static string SearchDoctors {
            get {
                return ResourceManager.GetString("SearchDoctors", resourceCulture);
            }
        }
        
        internal static string SearchPatients {
            get {
                return ResourceManager.GetString("SearchPatients", resourceCulture);
            }
        }
        
        internal static string SearchReceptionists {
            get {
                return ResourceManager.GetString("SearchReceptionists", resourceCulture);
            }
        }
        
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        internal static string FirstName_ {
            get {
                return ResourceManager.GetString("FirstName_", resourceCulture);
            }
        }
        
        internal static string LastName_ {
            get {
                return ResourceManager.GetString("LastName_", resourceCulture);
            }
        }
        
        internal static string MiddleName_ {
            get {
                return ResourceManager.GetString("MiddleName_", resourceCulture);
            }
        }
        
        internal static string BirthDate_ {
            get {
                return ResourceManager.GetString("BirthDate_", resourceCulture);
            }
        }
        
        internal static string CareerStartedDate_ {
            get {
                return ResourceManager.GetString("CareerStartedDate_", resourceCulture);
            }
        }
        
        internal static string Specialization_ {
            get {
                return ResourceManager.GetString("Specialization_", resourceCulture);
            }
        }
        
        internal static string Status_ {
            get {
                return ResourceManager.GetString("Status_", resourceCulture);
            }
        }
        
        internal static string Patient {
            get {
                return ResourceManager.GetString("Patient", resourceCulture);
            }
        }
        
        internal static string Receptionist {
            get {
                return ResourceManager.GetString("Receptionist", resourceCulture);
            }
        }
        
        internal static string CreateProfile {
            get {
                return ResourceManager.GetString("CreateProfile", resourceCulture);
            }
        }
        
        internal static string Office_ {
            get {
                return ResourceManager.GetString("Office_", resourceCulture);
            }
        }
    }
}
