//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RespounseMessages {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RespounseMessages() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Application.Resources.RespounseMessages", typeof(RespounseMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string NoContent {
            get {
                return ResourceManager.GetString("NoContent", resourceCulture);
            }
        }
        
        internal static string InternalServerError {
            get {
                return ResourceManager.GetString("InternalServerError", resourceCulture);
            }
        }
        
        internal static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        internal static string PatientNotFound {
            get {
                return ResourceManager.GetString("PatientNotFound", resourceCulture);
            }
        }
        
        internal static string OfficeNotFound {
            get {
                return ResourceManager.GetString("OfficeNotFound", resourceCulture);
            }
        }
        
        internal static string DoctorNotFound {
            get {
                return ResourceManager.GetString("DoctorNotFound", resourceCulture);
            }
        }
        
        internal static string SpecializationNotFound {
            get {
                return ResourceManager.GetString("SpecializationNotFound", resourceCulture);
            }
        }
        
        internal static string DoctorDoNotHaveThisSpecialization {
            get {
                return ResourceManager.GetString("DoctorDoNotHaveThisSpecialization", resourceCulture);
            }
        }
        
        internal static string DoctorIsNotInOffice {
            get {
                return ResourceManager.GetString("DoctorIsNotInOffice", resourceCulture);
            }
        }
        
        internal static string ServiceNotFound {
            get {
                return ResourceManager.GetString("ServiceNotFound", resourceCulture);
            }
        }
        
        internal static string TimeIsNotFree {
            get {
                return ResourceManager.GetString("TimeIsNotFree", resourceCulture);
            }
        }
        
        internal static string AppointmentNotFound {
            get {
                return ResourceManager.GetString("AppointmentNotFound", resourceCulture);
            }
        }
    }
}
